const $=id=>document.getElementById(id);
let connected=false,busy=false,savedLogin=false,orderSnapshot=null,currentDay=null,currentEstimate=null,importText=null,previewReady=false;
const istFormat=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'medium'});
function istDate(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`;}
$('orderDate').value=istDate();
function money(id,value){const el=$(id);el.textContent=typeof value!=='number'?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(value);el.classList.toggle('positive',value>0);el.classList.toggle('negative',value<0);}
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Neo-Request':'1'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed.');return d;}
function state(value){connected=value;$('login').hidden=value;$('logout').hidden=!value;$('refresh').disabled=!value;$('saveBrokerage').disabled=!value;$('previewImport').disabled=!value;$('mode').textContent=value?'Connected to Kotak Neo':'Not connected';$('connectionTitle').textContent=value?'Account connected':'Connect your account';document.dispatchEvent(new CustomEvent('neo-connection',{detail:value}));}
function table(id,result){const box=$(id);box.replaceChildren();if(!result||result.error||!result.rows?.length){const p=document.createElement('div');p.className='empty';p.textContent=result?.error||'No records.';box.append(p);return;}const t=document.createElement('table'),head=t.createTHead().insertRow();Object.keys(result.rows[0]).forEach(k=>{const th=document.createElement('th');th.textContent=k;head.append(th);});const body=t.createTBody();result.rows.forEach(r=>{const tr=body.insertRow();Object.entries(r).forEach(([k,v])=>{const td=tr.insertCell();td.textContent=v==null?'—':typeof v==='number'?v.toLocaleString('en-IN',{maximumFractionDigits:2}):String(v);if(k.includes('(IST)')&&typeof v==='string'){td.textContent=v.slice(0,10)+'\n'+v.slice(11,19);td.className='timecell';}if(k.includes('availability'))td.className='notecell';if((k.includes('P&L')||k==='Net')&&typeof v==='number')td.className=v>0?'positive':v<0?'negative':'';});});box.append(t);}
function filterOrders(){if(!orderSnapshot||orderSnapshot.error){table('orders',orderSnapshot);$('orderSummary').textContent='No order snapshot available.';return;}const all=orderSnapshot.rows||[],day=$('orderDate').value,from=$('orderFrom').value||'00:00',to=$('orderTo').value||'23:59';if(from>to){table('orders',{error:'From must precede Through.'});return;}const shown=all.filter(r=>{const t=r['Order time (IST)'];if(!t)return !day&&from==='00:00'&&to==='23:59';return (!day||t.slice(0,10)===day)&&t.slice(11,16)>=from&&t.slice(11,16)<=to;});table('orders',shown.length?{rows:shown}:{error:'No fetched orders match. This does not establish that no historical trades occurred.'});const dates=[...new Set(all.map(r=>r['Order time (IST)']?.slice(0,10)).filter(Boolean))].sort();$('orderSummary').textContent=`Showing ${shown.length} of ${all.length}. Fetched dates: ${dates.join(', ')||'unknown'}. Unknown timestamps appear with all filters cleared.`;}
function showHistory(h){money('historyNet',h?.confirmed_net);money('lifetimeNet',h?.lifetime_net);if(h?.lifetime_net==null)$('lifetimeNet').textContent='Not verified';$('historyCount').textContent=h?.confirmed?.length||0;$('historyCoverage').textContent=h?.coverage||'No historical statements imported. Estimates are separate.';table('confirmedRows',{rows:(h?.confirmed||[]).map(r=>({Date:r.date,'Gross P&L':r.gross_pnl,Charges:Math.round((r.gross_pnl-r.net)*100)/100,Net:r.net,'Contract note':r.contract_note,Ledger:r.ledger_reference}))});table('estimateRows',{rows:(h?.estimates||[]).map(r=>({Date:r.date,'Gross P&L':r.gross,'Estimated charges':r.fees?.total,'Estimated net':r.net,Status:'Estimate only'}))});const today=(h?.confirmed||[]).find(r=>r.date===currentDay);$('todayConfirmed').textContent=today?`Statement-confirmed net for ${currentDay}: ₹${today.net.toFixed(2)}. Stored once in history; live estimate remains separate.${currentEstimate===null?'':' Difference from estimate: ₹'+(today.net-currentEstimate).toFixed(2)}`:'No statement-confirmed record for today yet.';}
function render(d){const t=d.today;currentEstimate=t?.net??null;currentDay=t?.date||null;$('todayTitle').textContent=`Today · ${currentDay||istDate()} IST · F&O`;money('grossPnl',t?.gross);money('feesPnl',t?.fees?.total);money('netPnl',t?.net);$('todayNotice').textContent=[...(t?.issues||[]),...(t?.fees?.issues||[]),t?.fees?.basis||''].join('\n');$('feeBreakdown').replaceChildren();for(const [k,v] of Object.entries(t?.fees?.breakdown||{})){const item=document.createElement('span');item.textContent=`${k.toUpperCase()}: ₹${v.toFixed(2)}`;$('feeBreakdown').append(item);}$('brokerage').value=d.brokerage_per_order??'';const p=d.positions;table('openPositions',p?.error?p:{rows:(p?.rows||[]).filter(r=>r.State==='Open')});table('closedPositions',p?.error?p:{rows:(p?.rows||[]).filter(r=>r.State!=='Open')});orderSnapshot=d.orders;filterOrders();showHistory(d.history);}
function clear(){render({});$('updated').textContent='No account data loaded.';importText=null;previewReady=false;$('statementFile').value='';$('verified').checked=false;$('replace').checked=false;$('confirmImport').disabled=true;table('importPreview',null);$('importMessage').textContent='';}
async function refresh(){if(busy)return;busy=true;$('refresh').disabled=true;$('message').textContent='Fetching F&O snapshot…';try{const d=await api('dashboard');render(d);$('updated').textContent='Fetched '+istFormat.format(new Date(d.fetched_at))+' IST — not execution time.';$('message').textContent=[d.positions,d.orders].some(s=>s?.error)?'A report failed; see the section message.':'';}catch(e){clear();$('message').textContent=e.message;try{if(!(await api('status')).connected)state(false);}catch{state(false);}}finally{busy=false;$('refresh').disabled=!connected;}}
$('login').onsubmit=async e=>{e.preventDefault();$('connect').disabled=true;$('message').textContent='Connecting…';const data=Object.fromEntries(new FormData(e.target));if(savedLogin){Object.keys(data).forEach(k=>{if(k!=='totp')delete data[k];});data.use_saved=true;}try{await api('login',data);e.target.reset();clear();state(true);await refresh();}catch(e){state(false);$('message').textContent=e.message;}finally{$('login').reset();$('connect').disabled=false;}};
$('refresh').onclick=refresh;$('logout').onclick=async()=>{try{await api('logout',{});}catch(e){$('message').textContent=e.message;}finally{clear();state(false);}};
$('saveBrokerage').onclick=async()=>{try{await api('brokerage',{amount:$('brokerage').value});await refresh();}catch(e){$('message').textContent=e.message;}};
['orderDate','orderFrom','orderTo'].forEach(id=>$(id).onchange=filterOrders);$('allDates').onclick=()=>{$('orderDate').value='';$('orderFrom').value='00:00';$('orderTo').value='23:59';filterOrders();};
$('accountToggle').onclick=()=>{const h=document.body.classList.toggle('account-collapsed');$('accountToggle').textContent=h?'Show account panel':'Hide account panel';$('accountToggle').setAttribute('aria-expanded',String(!h));};
$('template').onclick=()=>{const csv='date,gross_pnl,brokerage,stt,exchange,sebi,stamp,ipft,gst,other,contract_note,ledger_reference\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='fno-confirmed-daily-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('statementFile').onchange=()=>{importText=null;previewReady=false;$('verified').checked=false;$('confirmImport').disabled=true;table('importPreview',null);};
$('verified').onchange=()=>{$('confirmImport').disabled=!previewReady||!$('verified').checked;};
$('previewImport').onclick=async()=>{try{const f=$('statementFile').files[0];if(!f)throw Error('Choose a mapped CSV file.');if(f.size>1500000)throw Error('CSV must be smaller than 1.5 MB.');importText=await f.text();const d=await api('import-preview',{csv:importText});table('importPreview',{rows:d.rows});previewReady=true;$('importMessage').textContent=`Preview: ${d.rows.length} dates; net ₹${d.net.toFixed(2)}. Verify before importing.`;$('confirmImport').disabled=!$('verified').checked;}catch(e){previewReady=false;$('confirmImport').disabled=true;$('importMessage').textContent=e.message;}};
$('confirmImport').onclick=async()=>{if(!previewReady)return;$('confirmImport').disabled=true;try{const d=await api('import-statements',{csv:importText,verified:$('verified').checked,replace:$('replace').checked});showHistory(d.history);$('importMessage').textContent=`Imported ${d.imported} daily records. Existing identical dates were not counted twice.`;previewReady=false;importText=null;}catch(e){$('importMessage').textContent=e.message;$('confirmImport').disabled=false;}};
api('status').then(async s=>{savedLogin=s.saved_login;$('manualLogin').hidden=savedLogin;$('loginHelp').textContent=savedLogin?'Your saved login is ready. Enter only your current TOTP.':'Enter your credentials to connect.';state(s.connected);if(s.connected)await refresh();else clear();}).catch(()=>{$('message').textContent='Cannot reach the local server.';});
$('saveCoverage').onclick=async()=>{try{const h=await api('coverage',{start:$('coverageStart').value,end:$('coverageEnd').value,attested:$('coverageAttest').checked});showHistory(h);$('coverageMessage').textContent='Coverage saved. Lifetime result is as of the verified-through date.';}catch(e){$('coverageMessage').textContent=e.message;}};
