/* Manual execution only. Broker credentials never enter this module. */
(()=>{
  let online=false, ready=false, working=false, polling=false, contracts=[], review=null, action='place', orderId=null;
  const el=id=>document.getElementById(id);
  const msg=text=>{el('tradeMessage').textContent=text;};
  const fmt=value=>value==null?'Unavailable':String(value);
  const ids=['tradeFind','tradeReview','tradeTrack','tradeSaveIp','tradeQuoteRefresh'];
  function controls(){ids.forEach(id=>el(id).disabled=!online||working);el('tradeConfirm').disabled=!online||!ready||working||!review||!el('tradeConfirmCheck').checked;}
  function invalidate(){review=null;el('tradeReviewBox').hidden=true;el('tradeConfirmCheck').checked=false;controls();}
  async function run(fn){if(working)return;working=true;controls();try{await fn();}catch(e){msg(e.message);}finally{working=false;controls();}}
  function newOrder(){invalidate();action='place';orderId=null;['tradeSide','tradeProduct','tradeContract'].forEach(id=>el(id).disabled=false);el('tradeActionInfo').textContent='New order';}
  async function status(){const s=await api('trading/status');ready=s.ready;el('tradeIp').value=s.configured_ip||'';el('tradeReadiness').textContent=s.ready?`Live submission configured for ${s.configured_ip}. Every order still requires review and confirmation.`:'Preview available. Live submission locked until static IP setup and a fresh login are complete.';controls();}
  function fillContracts(rows,selectId){contracts=rows;el('tradeContract').replaceChildren(new Option(rows.length?'Select exact contract':'No matching active contracts',''));for(const c of rows)el('tradeContract').add(new Option(`${c.symbol} | ${c.expiry} | ${c.kind} ${c.strike??''} | lot ${c.lot}`,c.id));if(selectId)el('tradeContract').value=selectId;}
  function selected(){return contracts.find(c=>c.id===el('tradeContract').value);}
  async function showQuote(){const c=selected();el('tradeQuote').textContent='Quote unavailable.';if(!c)return;const q=await api('trading/quote',{contract_id:c.id});let bt=q.broker_timestamp;const secs=Number(bt);if(bt&&Number.isFinite(secs)&&secs>0)bt=istFormat.format(new Date(secs*1000))+' IST';el('tradeQuote').textContent=`LTP ₹${fmt(q.ltp)} · Bid ₹${fmt(q.bid)} · Ask ₹${fmt(q.ask)} · Broker update: ${fmt(bt)} · Fetched ${istFormat.format(new Date(q.fetched_at))} IST`;
  }
  function contractInfo(){const c=selected();el('tradeContractInfo').textContent=c?`${c.segment.toUpperCase()} · Expiry ${c.expiry} · ${c.lot} units per lot · Tick ₹${c.tick} · ${Number(el('tradeLots').value)*c.lot} units selected`:'';if(c){el('tradePrice').step=c.tick;el('tradePrice').min=c.tick;el('tradeTrigger').step=c.tick;el('tradeTrigger').min=c.tick;}}
  function body(){return {action,order_id:orderId,contract_id:el('tradeContract').value,side:el('tradeSide').value,product:el('tradeProduct').value,lots:el('tradeLots').value,type:el('tradeType').value,price:el('tradePrice').value,trigger:el('tradeTrigger').value};}
  function displayReview(r){review=r;el('tradeConfirmCheck').checked=false;const p=r.params,c=r.contract,rows=[{'Field':'Action','Value':r.action.toUpperCase()},{Field:'Contract',Value:`${c.symbol} · ${c.segment} · expiry ${c.expiry}`},{Field:'Order ID',Value:p.order_id||'New order'}];
    if(r.action==='cancel'){rows.push({Field:'Current status',Value:r.existing.status},{Field:'Filled units (remain executed)',Value:r.existing.filled},{Field:'Requested units',Value:r.existing.quantity});}
    else{rows.push(...Object.entries({'Side':p.transaction_type==='B'?'BUY':'SELL','Product':p.product,'Units':p.quantity,'Lots':Number(p.quantity)/c.lot,'Limit price':`₹${p.price}`,'Trigger':p.trigger_price,'Validity':'DAY','Order type':p.order_type,'Estimated charges, this side only':r.fees?.total==null?'Unavailable for this exchange/date':`₹${r.fees.total}`,'Broker order margin':r.margin?.ordMrgn,'Broker available cash':r.margin?.avlCash,'Broker additional required margin':r.margin?.reqdMrgn}).map(([Field,Value])=>({Field,Value})));if(r.fees?.breakdown)rows.push(...Object.entries(r.fees.breakdown).map(([k,v])=>({Field:`Estimated ${k}`,Value:`₹${v}`})));}
    table('tradeReviewTable',{rows});el('tradeReviewNotice').textContent=`Review expires in ${r.expires_in} seconds. ${r.action==='cancel'?'Cancellation can race with a fill; wait for broker confirmation.':'Charges assume full execution at the entered limit and ₹0 API brokerage on an eligible plan. They are estimates for this order side, not a round trip or guaranteed net P&L. Contract notes determine final charges.'} ${r.fees?.issues?.join(' ')||''}`;el('tradeReviewBox').hidden=false;controls();el('tradeReviewBox').scrollIntoView({block:'nearest',behavior:'smooth'});
  }
  async function preview(){invalidate();const r=await api('trading/preview',body());displayReview(r);msg('Review ready. No order has been submitted.');}
  function actionTable(id,rows,columns,buttons){const box=el(id);box.replaceChildren();if(!rows.length){box.textContent='No records.';return;}const t=document.createElement('table'),head=t.createTHead().insertRow();for(const title of [...Object.values(columns),'Actions']){const th=document.createElement('th');th.textContent=title;head.append(th);}const b=t.createTBody();rows.forEach(row=>{const tr=b.insertRow();Object.keys(columns).forEach(k=>tr.insertCell().textContent=fmt(row[k]));const td=tr.insertCell();td.className='trade-actions';for(const [label,fn] of buttons(row)){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent=label;button.disabled=working;button.onclick=()=>run(()=>fn(row));td.append(button);}});box.append(t);}
  async function loadFor(row,nextAction){newOrder();msg('Resolving the exact contract…');const c=(await api('trading/resolve',{action:nextAction,order_id:row.id,symbol:row.symbol,segment:row.segment,product:row.product})).contract;fillContracts([c],c.id);action=nextAction;orderId=row.id||null;el('tradeSide').value=nextAction==='exit'?(row.quantity>0?'S':'B'):row.side;el('tradeProduct').value=row.product;el('tradeLots').value=Math.abs(row.quantity)/c.lot;el('tradePrice').value=nextAction==='exit'?'':row.price||'';el('tradeType').value=nextAction==='exit'?'L':row.type;el('tradeTrigger').value=row.trigger||'';['tradeSide','tradeProduct','tradeContract'].forEach(id=>el(id).disabled=true);el('tradeTriggerLabel').hidden=el('tradeType').value!=='SL';el('tradeActionInfo').textContent=nextAction==='exit'?`EXIT ${row.symbol}: opposite-side order; choose a limit price.`:`${nextAction.toUpperCase()} order ${row.id}. Modified quantity is the TOTAL, including filled units.`;contractInfo();if(nextAction==='cancel')await preview();else{await showQuote();msg('Ticket prepared. Set your price and review before confirming.');el('tradeTicket').scrollIntoView({block:'center',behavior:'smooth'});}}
  async function tracking(){if(!online||polling)return;polling=true;try{const d=await api('trading/tracking');table('tradeIntents',{rows:d.intents.map(r=>({'Requested (IST)':r.created,Action:r.action,Symbol:r.symbol,'Request state':r.state,'Order ID':r.order_id,Details:r.message}))});actionTable('tradeOrders',d.orders,{id:'Order ID',symbol:'Contract',side:'Side',product:'Product',quantity:'Units',filled:'Filled',average:'Average',price:'Limit',status:'Broker status',reason:'Rejection reason'},r=>r.manageable?[['Modify',x=>loadFor(x,'modify')],['Cancel',x=>loadFor(x,'cancel')]]:[]);actionTable('tradePositions',d.positions,{symbol:'Contract',product:'Product',quantity:'Net units'},()=>[['Exit',x=>loadFor(x,'exit')]]);if(d.positions_error)el('tradePositions').textContent=d.positions_error;el('tradeTrackingTime').textContent=`Order book fetched ${istFormat.format(new Date(d.fetched_at))} IST. Acknowledgement is not execution. Auto-refresh every 5 seconds while visible.`;}catch(e){el('tradeTrackingTime').textContent='Tracking unavailable; displayed values are stale. '+e.message;el('tradeOrders').querySelectorAll('button').forEach(b=>b.disabled=true);el('tradePositions').querySelectorAll('button').forEach(b=>b.disabled=true);}finally{polling=false;}}
  el('tradeSearch').onsubmit=e=>{e.preventDefault();run(async()=>{newOrder();fillContracts([]);el('tradeQuote').textContent='Select a contract.';const d=await api('trading/search',{segment:el('tradeSegment').value,symbol:el('tradeSymbol').value,kind:el('tradeKind').value,expiry:el('tradeExpiry').value,strike:el('tradeStrike').value});fillContracts(d.contracts);msg(`${d.contracts.length} active contracts found${d.contracts.length===300?' (limited to 300; narrow expiry/strike)':''}. Select the exact contract.`);});};
  el('tradeContract').onchange=()=>{invalidate();contractInfo();run(showQuote);};
  el('tradeTicket').addEventListener('input',()=>{invalidate();contractInfo();});el('tradeType').onchange=()=>{invalidate();el('tradeTriggerLabel').hidden=el('tradeType').value!=='SL';};
  el('tradeTicket').onsubmit=e=>{e.preventDefault();run(preview);};el('tradeQuoteRefresh').onclick=()=>run(showQuote);el('tradeNew').onclick=newOrder;el('tradeBack').onclick=invalidate;el('tradeConfirmCheck').onchange=controls;
  el('tradeConfirm').onclick=()=>run(async()=>{if(!review||!ready||!el('tradeConfirmCheck').checked)return;const id=review.review_id;invalidate();msg('Submitting once. Waiting for Kotak acknowledgement…');try{const r=await api('trading/confirm',{review_id:id,confirmed:true});msg(r.message);}catch(e){msg(e.message+' Refresh execution tracking before any replacement order.');}await tracking();});
  el('tradeTrack').onclick=()=>run(tracking);
  el('tradeIpForm').onsubmit=e=>{e.preventDefault();run(async()=>{const d=await api('trading/configure',{ip:el('tradeIp').value,attested:el('tradeIpAttest').checked});ready=false;invalidate();msg(d.message);await status();});};
  document.addEventListener('neo-connection',e=>{online=e.detail;ready=false;newOrder();fillContracts([]);table('tradeIntents',null);el('tradeOrders').replaceChildren();el('tradePositions').replaceChildren();el('tradeQuote').textContent='Select a contract.';el('tradeContractInfo').textContent='';msg('');controls();if(online){status().catch(e=>msg(e.message));tracking();}else el('tradeReadiness').textContent='Connect to prepare an order. Disconnecting does not cancel broker orders.';});
  // The account-status fetch can finish before this second script loads.
  document.dispatchEvent(new CustomEvent('neo-connection',{detail:connected}));
  setInterval(()=>{if(online&&!working&&!document.hidden)tracking();},5000);
})();
